default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: quez_challenge_development

test:
  <<: *default
  database: quez_challenge_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: quez_challenge_production
